
- name: "Add vim paths to list"
  set_fact:
    fetch_service_config: "{{ fetch_service_config | combine({item.key: (fetch_service_config[item.key] | default([]) | union(item.value))}) }}"
  with_dict:
    user_paths: "{{vim_user_config_paths}}"


